### ISSUE TITLE
Mantenimiento de GitHub

### ISSUE THREAD

**Issue by VictoriaCalbet** [InnosoftDaysPresidencia/Finanzas#16]

**Comment by alexgs922** [comment]
Me imputo unos 

> **20 minutos**

 de mantenimiento de Github, en los que van incluidos creación, asignación, revisión y ordenación de issues.

**Comment by VictoriaCalbet** [comment]
Perdón por borrar la tarea esta de "in progress" del grupo de tarde, quise agregarla, pero no podía.

**Comment by alexgs922** [comment]
En las últimas tareas de mantenimiento y administración de git unos 

> **20 min**

**Comment by alexgs922** [comment]
He tardado

>  **45 min**

 en las últimas tareas de github
