### ISSUE TITLE
Ayudas/Becas/Burocracía

### ISSUE THREAD

**Issue by alexgs922** [InnosoftDaysPresidencia/Finanzas#20]
Buscar información en Delegación de alumnos.

**Comment by Taxo16** [comment]
Gestión con delegación e impresión de los primeros folletos terminada.

**Comment by Taxo16** [comment]
Impresión de folletos tripticos, carteles, y papeletas con la financiación de la delegación de alumnos terminada.

**Comment by alexgs922** [comment]
Perfecto, se cierra el issue.
