### ISSUE TITLE
Financiación por parte de Sugus

### ISSUE THREAD

**Issue by alexgs922** [InnosoftDaysPresidencia/Finanzas#23]
Proponer que forme parte de la financiación de las jornadas con lo que crean conveniente.

**Comment by Taxo16** [comment]
El acuerdo con Sugus para usar una cuenta de la asociación fue aceptado y firmado. Esta tarea duró 45 min. Solicito que se cierre.

**Comment by alexgs922** [comment]
Recibido. Procedo a cerrar el issue.
