### ISSUE TITLE
Organización 

### ISSUE THREAD

**Issue by alexgs922** [InnosoftDaysPresidencia/Finanzas#35]
Ayudando en la organización y en la mesa de registro para el día de jornada 06/11/2017

**Comment by fblanco89** [comment]
He estado ayudando en la jornada de hoy(06/11/2017) de varias formas, mediante impresión de carteles, de identificaciones, con las papeletas.

**Comment by samusfc** [comment]
He estado ayudando en la jornada de hoy(06/11/2017) de varias formas, mediante impresión de carteles, de identificaciones, con las papeletas.

**Comment by alexgs922** [comment]
Estuve ayudando en la realización del sorteo de la raspberry pi ayer, 9 de Noviembre.

**Comment by Taxo16** [comment]
Estuve ayudando en la mesa de registro el día 6 y 9 de Noviembre supervisando la venta de papeletas, y el día 9 en la realización del sorteo de las papeletas. 
Solicito el cierre del issue.

**Comment by alexgs922** [comment]
Se cierra.
