### ISSUE TITLE
Coordinación

### ISSUE THREAD

**Issue by alexgs922** [InnosoftDaysPresidencia/Finanzas#36]
Puesta en marcha de opiniones y coordinación entre coordinador y secretario.

**Comment by alexgs922** [comment]
Hemos mantenido una coordinación fluida tanto por correo y por telegram de 3 horas.

**Comment by Taxo16** [comment]
Solicito el cierre del issue por la finalización de las jornadas.

**Comment by alexgs922** [comment]
Procedo.
