### ISSUE TITLE
Asistencia a las jornadas

### ISSUE THREAD

**Issue by alexgs922** [InnosoftDaysPresidencia/Finanzas#38]
Tarea de asistir a las jornadas que finalmente cuentan.

**Comment by alexgs922** [comment]
He asistido durante **2 horas y 10 minutos** desde las 15:30 hasta las 17: 50 de la última charla el Lunes 06 de Noviembre de 2017.

**Comment by fblanco89** [comment]
He asistido de 08:30 a 10:30, de 12:30 a 13:15 y de 15.30 a 17.50.

**Comment by enruiq** [comment]
He asistido de 15:30 a 16:00.

**Comment by samusfc** [comment]
He asistido de 9:30 a 10:20, 12:45 a 13:15 y de 15:30 a 17:30.

**Comment by hannacheikh11** [comment]
he asitido desde de 12:30 a 13:15 y 13h15 a14h20 y  de 15.30 a 17.50.

2017-11-07 16:22 GMT+01:00 VictoriaCalbet <notifications@github.com>:

**Comment by Taxo16** [comment]
El lunes asistí de 9:30 a 10:20, de 12:45 a 13:15 y de 15:30 a 17:30

**Comment by alexgs922** [comment]
Ayer día 9 de Noviembre, asistí a todas las charlas que se impartieron en el aula A1.16 desde las 15:30 hasta las 19:40 que duró la última charla.

**Comment by Taxo16** [comment]
Asistí el 9 de noviembre a las conferencias de 15:30 a 16:50, de 18:00 a 18:30 y de 18:40 a 19:30

**Comment by hannacheikh11** [comment]
Asistí el 9 de noviembre a las conferencias de 10h30 a 11h30 y 11h30 a
12h30 de  y15:30-16:10 y 16h15 a 16h50 y 16h50 18h00 de 18:00 a 18:30 y de
18:40 a 19:30

**Comment by samusfc** [comment]
Asistí el 9 de noviembre a las conferencias de 11:30 a 12:30 y a todas las de la tarde, de 15:30 a 19:40.

**Comment by fblanco89** [comment]
Asistí el 9 de noviembre a las conferencias de 11:30 a 12:30 y por la tarde a partir desde las 16:15 hasta las 19:30.

**Comment by Felix866** [comment]
He asistido el 6 de noviembre de 12:45 a 13:15 y de 15:30 a 17:30. 
El día 9 de noviembre de 10:40 a 12:30 y de 17:00 a 19:30

**Comment by enruiq** [comment]
He asistido el 9 de Noviembre de 15:30 a 19:40 a las charlas de las Jornadas.
Total: 4h 10m

**Comment by enruiq** [comment]
Solicito el cierre de la issue

**Comment by alexgs922** [comment]
Perfecto, se procede al cierre del issue entonces.
